// PDF export utility using jsPDF + autotable
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export function exportPDF(result) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const { student_name, calculation: c, prediction: p, recommendations, input } = result;

  // Header
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, 210, 40, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('AttendIQ', 14, 18);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(148, 163, 184);
  doc.text('College Attendance Report', 14, 27);
  doc.setTextColor(100, 160, 255);
  doc.text(new Date().toLocaleDateString(), 14, 34);

  // Student name
  doc.setTextColor(241, 245, 249);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(student_name, 14, 55);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(148, 163, 184);
  doc.text(`Min. Requirement: ${input.min_requirement}%  |  Future Classes: ${input.future_classes}`, 14, 62);

  // Status badge
  const statusColors = { eligible: [34, 197, 94], warning: [245, 158, 11], danger: [239, 68, 68] };
  const [r, g, b] = statusColors[c.status] || [148, 163, 184];
  doc.setFillColor(r, g, b);
  doc.roundedRect(14, 68, 55, 9, 2, 2, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text(c.status_label.toUpperCase(), 17, 74);

  // Stats table
  autoTable(doc, {
    startY: 82,
    head: [['Metric', 'Value']],
    body: [
      ['Current Attendance', `${c.current_pct}%`],
      ['Predicted Attendance', `${p.predicted_pct}%`],
      ['Classes Attended', `${input.attended_classes} / ${input.total_classes}`],
      ['Missed Classes', c.missed_classes],
      ['Classes Needed for Target', c.classes_needed],
      ['Max Classes Can Miss', c.max_missable],
    ],
    headStyles: { fillColor: [30, 41, 59], textColor: [148, 163, 184], fontStyle: 'bold' },
    bodyStyles: { fillColor: [22, 32, 50], textColor: [241, 245, 249] },
    alternateRowStyles: { fillColor: [26, 38, 57] },
    theme: 'plain',
  });

  // Model info
  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 10,
    head: [['ML Model Performance', '']],
    body: [
      ['Algorithm', 'Random Forest Regressor'],
      ['Model Accuracy (R²)', `${(p.model_r2 * 100).toFixed(1)}%`],
      ['Prediction Confidence', `${p.confidence}%`],
    ],
    headStyles: { fillColor: [30, 41, 59], textColor: [148, 163, 184] },
    bodyStyles: { fillColor: [22, 32, 50], textColor: [241, 245, 249] },
    theme: 'plain',
  });

  // Recommendations
  if (recommendations?.length) {
    doc.setTextColor(148, 163, 184);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('Recommendations', 14, doc.lastAutoTable.finalY + 18);
    recommendations.forEach((rec, i) => {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(200, 210, 230);
      doc.text(`• ${rec.text}`, 14, doc.lastAutoTable.finalY + 26 + i * 8);
    });
  }

  // Footer
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 280, 210, 17, 'F');
  doc.setTextColor(71, 85, 105);
  doc.setFontSize(8);
  doc.text('Generated by AttendIQ · ML-powered Attendance Predictor', 14, 290);

  doc.save(`attendance_report_${student_name.replace(/\s+/g, '_')}.pdf`);
}
